language: node_js
node_js:
  - "10"

script: echo "Running tests against $(node -v)..."

jobs:
  include:
    - stage: Produce Coverage
      node_js: "10"
      script: test --coverage --coverageReporters=text-lcov | ./node_modules/coveralls/bin/coveralls.js